const allLimit = [{
  "icon": "&#xe640;",
  "iconSize": "24",
  "level": 1,
  "sort": 1,
  "state": 1,
  "link": "/Index/Index",
  "name": "首页",
  "children": []
}, {
  "icon": "&#xe640;",
  "iconSize": "24",
  "level": 1,
  "sort": 2,
  "state": 1,
  "link": "/Directive/Directive",
  "name": "vue自定义指令",
  "children": []
}, {
  "icon": "&#xe640;",
  "iconSize": "24",
  "level": 1,
  "sort": 3,
  "state": 1,
  "link": "/Program/Program",
  "name": "节目管理",
  "children": [{
    "icon": "&#xe640;",
    "iconSize": "24",
    "level": 2,
    "sort": 4,
    "state": 1,
    "link": "/Program/ProgramList/ProgramList",
    "name": "节目列表",
    "parentName": "节目管理",
    "children": []
  }]
}, {
  "icon": "&#xe640;",
  "iconSize": "24",
  "level": 1,
  "sort": 5,
  "state": 1,
  "link": "/User",
  "name": "用户管理",
  "children": [{
    "icon": "&#xe640;",
    "iconSize": "24",
    "level": 2,
    "sort": 6,
    "state": 1,
    "link": "/User/UserAuth/UserAuth",
    "name": "用户权限",
    "parentName": "用户管理",
    "children": []
  }, {
    "icon": "&#xe640;",
    "iconSize": "24",
    "level": 2,
    "sort": 7,
    "state": 1,
    "link": "/User/UserList/UserList",
    "name": "用户列表",
    "parentName": "用户管理",
    "children": []
  }]
}, {
  "icon": "&#xe640;",
  "iconSize": "24",
  "level": 1,
  "sort": 13,
  "state": 1,
  "link": "/System",
  "name": "系统设置",
  "children": [{
    "icon": "&#xe640;",
    "iconSize": "20",
    "level": 2,
    "sort": 14,
    "state": 1,
    "link": "/System/User/User",
    "name": "用户管理",
    "parentName": "系统设置",
    "children": []
  }, {
    "icon": "&#xe640;",
    "iconSize": "20",
    "level": 2,
    "sort": 15,
    "state": 1,
    "link": "/System/Log/Log",
    "name": "系统日志",
    "parentName": "系统设置",
    "children": []
  }]
}]

const nowLimit = [{
  "icon": "&#xe640;",
  "iconSize": "24",
  "level": 1,
  "sort": 1,
  "state": 1,
  "link": "/Index/Index",
  "name": "首页",
  "children": []
}, {
  "icon": "&#xe640;",
  "iconSize": "24",
  "level": 1,
  "sort": 3,
  "state": 1,
  "link": "/Live/Live",
  "name": "节目管理",
  "children": [{
    "icon": "&#xe640;",
    "iconSize": "24",
    "level": 2,
    "sort": 4,
    "state": 1,
    "link": "/LiveType/LiveType",
    "name": "直播分类",
    "parentName": "节目管理",
    "children": []
  }, {
    "icon": "&#xe640;",
    "iconSize": "24",
    "level": 2,
    "sort": 5,
    "state": 1,
    "link": "/Live/Live",
    "name": "直播列表",
    "parentName": "节目管理",
    "children": []
  }]
}, {
  "icon": "&#xe640;",
  "iconSize": "24",
  "level": 1,
  "sort": 6,
  "state": 1,
  "link": "/User",
  "name": "用户管理",
  "children": [{
    "icon": "&#xe640;",
    "iconSize": "24",
    "level": 2,
    "sort": 7,
    "state": 1,
    "link": "/User/UserList/UserList",
    "name": "用户列表",
    "parentName": "用户管理",
    "children": []
  }]
}]
export {
  allLimit,
  nowLimit
}